use [AdventureWorks]

--triggers - found in drop down of a certain table
SELECT * FROM [HumanResources].[Shift]

-- TRIGGER TO ROLLBACK IF A NEW SHIFT GETS CREATED WITHOUT MANAG APPROV
CREATE TRIGGER Demo_trigger
ON [HumanResources].[Shift]
AFTER INSERT
AS
BEGIN
PRINT 'INSERT NOT ALLOWED, NEEDS APPROVAL'
ROLLBACK TRANSACTION
END
GO

-- CHECK IT IS NOW IN THE TABLE DROP DOWN
-- TEST TRIGGER
INSERT INTO [HumanResources].[Shift]
(
[Name],
[StartTime],
[EndTime],
[ModifiedDate])
VALUES
('GEORGE SHIFT',
'07:00:00.0000000',
'08:00:00.0000000',
GETDATE())

-- SHOULD GET INSERT NOT ALLOWED NEEDS APPROVAL

--rollback stopped from being done
SELECT * FROM [HumanResources].[Shift]

--trigger at db level (database level trigger)
CREATE TRIGGER DEMO_DBTRIGGER
ON DATABASE
AFTER CREATE_TABLE
AS
BEGIN
PRINT 'CREATION OF NEW TABLE NOT ALLOWED'
ROLLBACK TRANSACTION
END
GO

-- CHECK THIS IS BLOCKED BY TRIGGER
CREATE TABLE MYDEMOTABLE(COL1 VARCHAR(20))